# frozen_string_literal: true

module Config
  ATTESTATION_SIGNING_KEY = ENV['ATTESTATION_SIGNING_KEY']
  BANK_GUID = ENV['BANK_GUID']
  BASE_URL = ENV['BASE_URL']
  CLIENT_ID = ENV['APPLICATION_CLIENT_ID']
  CLIENT_SECRET = ENV['APPLICATION_CLIENT_SECRET']
  TIMEOUT = ENV.fetch('TIMEOUT', 30).to_i
  VERIFICATION_KEY_GUID = ENV['VERIFICATION_KEY_GUID']
end
